config/routes.rb
Congresos::Application.routes.draw do
  resources :eventos

  resources :tipo_eventos

  resources :asistencia

  resources :personas

  
  get "inicio/home", :as => :home

 
  delete "logout" => "user_sessions#destroy", :as => :logout
  
  resource :user_session, :excep => :destroy

  resources :users

  root :to => 'inicio#home'

end

app/models/asistencia.rb
class Asistencia < ActiveRecord::Base
end

app/models/campo.rb
class Campo < ActiveRecord::Base
  validates :nombre, :presence => true
  has_and_belongs_to_many :congresos
end

app/models/campos_congreso.rb
class CamposCongreso < ActiveRecord::Base

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/congresos_user.rb
class CongresosUser < ActiveRecord::Base
  
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_one :factura
  has_many :personas
end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  has_one :factura
end

app/models/persona.rb
class Persona < ActiveRecord::Base
end

app/models/registro_cl2.rb
class RegistroCl2 < ActiveRecord::Base
  belongs_to :persona
end

app/models/tipo_evento.rb
class TipoEvento < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |config|
    #Configuration Options
    config.crypto_provider = Authlogic::CryptoProviders::MD5
  end
  
has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100>"}

  has_and_belongs_to_many :congresos

  easy_roles :roles

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :login,  :presence => true,
                    :length   => { :maximum => 20 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => true
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    [session_key]
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @evento = Evento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.json
  def new
    @evento = Evento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @evento = Evento.find(params[:id])
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render json: @evento, status: :created, location: @evento }
      else
        format.html { render action: "new" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.json
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate
  #before_filter :administrador?, :only => [:index, :create, :destroy, :new, :edit]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if params[:admin] == "1"
      @user.add_role 'admin'
    end
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario actualizado correctamente.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paperclip_url(attachment)
    #FixMe: Esto debe buscar la url actual
    if Rails.env == "production"
      "http://congresos.uach.mx#{attachment.url}"
    elsif Rails.env == "development"
      "http://localhost:3000#{attachment.url}"
    end
  end

  def imagen?(nombre_archivo)
    nombre_separado = nombre_archivo.split "."
    extension = nombre_separado.last
    extension == "png" or extension == "jpg" or extension == "jpg" or extension == "gif"
  end
end

app/helpers/asistencia_helper.rb
module AsistenciaHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/tipo_eventos_helper.rb
module TipoEventosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :tipo_evento_id %><br />
    <%= f.number_field :tipo_evento_id %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha, :order => [:day,:month,:year] %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br />
    <%= f.text_field :ubicacion %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :cupo %><br />
    <%= f.number_field :cupo %>
  </div>
  <div class="field">
    <%= f.label :hora %><br />
    <%= f.time_select :hora %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editar evento</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @evento %> |
<%= link_to 'Regresar', eventos_path %>

app/views/eventos/index.html.erb
<h1>Programación de Eventos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Tipo evento</th>
    <th>Fecha</th>
    <th>Ubicacion</th>
    <th>Descripcion</th>
    <th>Cupo</th>
    <th>Hora</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eventos.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.tipo_evento_id %></td>
    <td><%= evento.fecha %></td>
    <td><%= evento.ubicacion %></td>
    <td><%= evento.descripcion %></td>
    <td><%= evento.cupo %></td>
    <td><%= evento.hora %></td>
    <td><%= link_to 'Mostrar', evento %></td>
    <td><%= link_to 'Editar', edit_evento_path(evento) %></td>
    <td><%= link_to 'Eliminar', evento, confirm: '¿Esta seguro de eliminar el evento?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Registrar nuevo evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>Nuevo evento</h1>

<%= render 'form' %>

<%= link_to 'Regresar', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @evento.nombre %>
</p>

<p>
  <b>Tipo evento:</b>
  <%= @evento.tipo_evento_id %>
</p>

<p>
  <b>Fecha:</b>
  <%= @evento.fecha %>
</p>

<p>
  <b>Ubicacion:</b>
  <%= @evento.ubicacion %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @evento.descripcion %>
</p>

<p>
  <b>Cupo:</b>
  <%= @evento.cupo %>
</p>

<p>
  <b>Hora:</b>
  <%= @evento.hora %>
</p>


<%= link_to 'Editar', edit_evento_path(@evento) %> |
<%= link_to 'Regresar', eventos_path %>