config/routes.rb
Congresos::Application.routes.draw do
  resources :eventos

  resources :tipo_eventos

  resources :asistencia

  resources :personas

  
  get "inicio/home", :as => :home

 
  delete "logout" => "user_sessions#destroy", :as => :logout
  
  resource :user_session, :excep => :destroy

  resources :users

  root :to => 'inicio#home'

end

app/models/asistencia.rb
class Asistencia < ActiveRecord::Base
end

app/models/campo.rb
class Campo < ActiveRecord::Base
  validates :nombre, :presence => true
  has_and_belongs_to_many :congresos
end

app/models/campos_congreso.rb
class CamposCongreso < ActiveRecord::Base

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/congresos_user.rb
class CongresosUser < ActiveRecord::Base
  
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_one :factura
  has_many :personas
end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  has_one :factura
end

app/models/persona.rb
class Persona < ActiveRecord::Base
end

app/models/registro_cl2.rb
class RegistroCl2 < ActiveRecord::Base
  belongs_to :persona
end

app/models/tipo_evento.rb
class TipoEvento < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |config|
    #Configuration Options
    config.crypto_provider = Authlogic::CryptoProviders::MD5
  end
  
has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100>"}

  has_and_belongs_to_many :congresos

  easy_roles :roles

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :login,  :presence => true,
                    :length   => { :maximum => 20 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => true
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    [session_key]
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @personas }
    end
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @persona = Persona.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @persona }
    end
  end

  # GET /personas/new
  # GET /personas/new.json
  def new
    @persona = Persona.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @persona }
    end
  end

  # GET /personas/1/edit
  def edit
    @persona = Persona.find(params[:id])
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(params[:persona])

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render json: @persona, status: :created, location: @persona }
      else
        format.html { render action: "new" }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /personas/1
  # PUT /personas/1.json
  def update
    @persona = Persona.find(params[:id])

    respond_to do |format|
      if @persona.update_attributes(params[:persona])
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona = Persona.find(params[:id])
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate
  #before_filter :administrador?, :only => [:index, :create, :destroy, :new, :edit]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if params[:admin] == "1"
      @user.add_role 'admin'
    end
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario actualizado correctamente.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paperclip_url(attachment)
    #FixMe: Esto debe buscar la url actual
    if Rails.env == "production"
      "http://congresos.uach.mx#{attachment.url}"
    elsif Rails.env == "development"
      "http://localhost:3000#{attachment.url}"
    end
  end

  def imagen?(nombre_archivo)
    nombre_separado = nombre_archivo.split "."
    extension = nombre_separado.last
    extension == "png" or extension == "jpg" or extension == "jpg" or extension == "gif"
  end
end

app/helpers/asistencia_helper.rb
module AsistenciaHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/tipo_eventos_helper.rb
module TipoEventosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apaterno %><br />
    <%= f.text_field :apaterno %>
  </div>
  <div class="field">
    <%= f.label :amaterno %><br />
    <%= f.text_field :amaterno %>
  </div>
  <div class="field">
    <%= f.label :ocupacion %><br />
    <%= f.text_field :ocupacion %>
  </div>
  <div class="field">
    <%= f.label :correo %><br />
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :comunidadOrigen %><br />
    <%= f.text_field :comunidadOrigen %>
  </div>
  <div class="field">
    <%= f.label :colonia %><br />
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label :nfam %><br />
    <%= f.number_field :nfam %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<h1>Listing personas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apaterno</th>
    <th>Amaterno</th>
    <th>Ocupacion</th>
    <th>Correo</th>
    <th>Comunidadorigen</th>
    <th>Colonia</th>
    <th>Nfam</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personas.each do |persona| %>
  <tr>
    <td><%= persona.nombre %></td>
    <td><%= persona.apaterno %></td>
    <td><%= persona.amaterno %></td>
    <td><%= persona.ocupacion %></td>
    <td><%= persona.correo %></td>
    <td><%= persona.comunidadOrigen %></td>
    <td><%= persona.colonia %></td>
    <td><%= persona.nfam %></td>
    <td><%= link_to 'Show', persona %></td>
    <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
    <td><%= link_to 'Destroy', persona, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @persona.nombre %>
</p>

<p>
  <b>Apaterno:</b>
  <%= @persona.apaterno %>
</p>

<p>
  <b>Amaterno:</b>
  <%= @persona.amaterno %>
</p>

<p>
  <b>Ocupacion:</b>
  <%= @persona.ocupacion %>
</p>

<p>
  <b>Correo:</b>
  <%= @persona.correo %>
</p>

<p>
  <b>Comunidadorigen:</b>
  <%= @persona.comunidadOrigen %>
</p>

<p>
  <b>Colonia:</b>
  <%= @persona.colonia %>
</p>

<p>
  <b>Nfam:</b>
  <%= @persona.nfam %>
</p>


<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>