config/routes.rb
Congresos::Application.routes.draw do
  resources :eventos

  resources :tipo_eventos

  resources :asistencia

  resources :personas

  
  get "inicio/home", :as => :home

 
  delete "logout" => "user_sessions#destroy", :as => :logout
  
  resource :user_session, :excep => :destroy

  resources :users

  root :to => 'inicio#home'

end

app/models/asistencia.rb
class Asistencia < ActiveRecord::Base
end

app/models/campo.rb
class Campo < ActiveRecord::Base
  validates :nombre, :presence => true
  has_and_belongs_to_many :congresos
end

app/models/campos_congreso.rb
class CamposCongreso < ActiveRecord::Base

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/congresos_user.rb
class CongresosUser < ActiveRecord::Base
  
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_one :factura
  has_many :personas
end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  has_one :factura
end

app/models/persona.rb
class Persona < ActiveRecord::Base
end

app/models/registro_cl2.rb
class RegistroCl2 < ActiveRecord::Base
  belongs_to :persona
end

app/models/tipo_evento.rb
class TipoEvento < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |config|
    #Configuration Options
    config.crypto_provider = Authlogic::CryptoProviders::MD5
  end
  
has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100>"}

  has_and_belongs_to_many :congresos

  easy_roles :roles

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :login,  :presence => true,
                    :length   => { :maximum => 20 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => true
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    [session_key]
  end
end

app/controllers/tipo_eventos_controller.rb
class TipoEventosController < ApplicationController
  # GET /tipo_eventos
  # GET /tipo_eventos.json
  def index
    @tipo_eventos = TipoEvento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipo_eventos }
    end
  end

  # GET /tipo_eventos/1
  # GET /tipo_eventos/1.json
  def show
    @tipo_evento = TipoEvento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipo_evento }
    end
  end

  # GET /tipo_eventos/new
  # GET /tipo_eventos/new.json
  def new
    @tipo_evento = TipoEvento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipo_evento }
    end
  end

  # GET /tipo_eventos/1/edit
  def edit
    @tipo_evento = TipoEvento.find(params[:id])
  end

  # POST /tipo_eventos
  # POST /tipo_eventos.json
  def create
    @tipo_evento = TipoEvento.new(params[:tipo_evento])

    respond_to do |format|
      if @tipo_evento.save
        format.html { redirect_to @tipo_evento, notice: 'Tipo evento was successfully created.' }
        format.json { render json: @tipo_evento, status: :created, location: @tipo_evento }
      else
        format.html { render action: "new" }
        format.json { render json: @tipo_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_eventos/1
  # PUT /tipo_eventos/1.json
  def update
    @tipo_evento = TipoEvento.find(params[:id])

    respond_to do |format|
      if @tipo_evento.update_attributes(params[:tipo_evento])
        format.html { redirect_to @tipo_evento, notice: 'Tipo evento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipo_evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_eventos/1
  # DELETE /tipo_eventos/1.json
  def destroy
    @tipo_evento = TipoEvento.find(params[:id])
    @tipo_evento.destroy

    respond_to do |format|
      format.html { redirect_to tipo_eventos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate
  #before_filter :administrador?, :only => [:index, :create, :destroy, :new, :edit]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if params[:admin] == "1"
      @user.add_role 'admin'
    end
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario actualizado correctamente.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paperclip_url(attachment)
    #FixMe: Esto debe buscar la url actual
    if Rails.env == "production"
      "http://congresos.uach.mx#{attachment.url}"
    elsif Rails.env == "development"
      "http://localhost:3000#{attachment.url}"
    end
  end

  def imagen?(nombre_archivo)
    nombre_separado = nombre_archivo.split "."
    extension = nombre_separado.last
    extension == "png" or extension == "jpg" or extension == "jpg" or extension == "gif"
  end
end

app/helpers/asistencia_helper.rb
module AsistenciaHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/tipo_eventos_helper.rb
module TipoEventosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tipo_eventos/_form.html.erb
<%= form_for(@tipo_evento) do |f| %>
  <% if @tipo_evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_evento.errors.count, "error") %> prohibited this tipo_evento from being saved:</h2>

      <ul>
      <% @tipo_evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_eventos/edit.html.erb
<h1>Editing tipo_evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_evento %> |
<%= link_to 'Back', tipo_eventos_path %>

app/views/tipo_eventos/index.html.erb
<h1>Listing tipo_eventos</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipo_eventos.each do |tipo_evento| %>
  <tr>
    <td><%= tipo_evento.tipo %></td>
    <td><%= tipo_evento.descripcion %></td>
    <td><%= link_to 'Show', tipo_evento %></td>
    <td><%= link_to 'Edit', edit_tipo_evento_path(tipo_evento) %></td>
    <td><%= link_to 'Destroy', tipo_evento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tipo evento', new_tipo_evento_path %>

app/views/tipo_eventos/new.html.erb
<h1>New tipo_evento</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_eventos_path %>

app/views/tipo_eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @tipo_evento.tipo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @tipo_evento.descripcion %>
</p>


<%= link_to 'Edit', edit_tipo_evento_path(@tipo_evento) %> |
<%= link_to 'Back', tipo_eventos_path %>