config/routes.rb
Congresos::Application.routes.draw do
  resources :eventos

  resources :tipo_eventos

  resources :asistencia

  resources :personas

  
  get "inicio/home", :as => :home

 
  delete "logout" => "user_sessions#destroy", :as => :logout
  
  resource :user_session, :excep => :destroy

  resources :users

  root :to => 'inicio#home'

end

app/models/asistencia.rb
class Asistencia < ActiveRecord::Base
end

app/models/campo.rb
class Campo < ActiveRecord::Base
  validates :nombre, :presence => true
  has_and_belongs_to_many :congresos
end

app/models/campos_congreso.rb
class CamposCongreso < ActiveRecord::Base

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/congresos_user.rb
class CongresosUser < ActiveRecord::Base
  
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_one :factura
  has_many :personas
end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
end

app/models/pais.rb
class Pais < ActiveRecord::Base
  has_one :factura
end

app/models/persona.rb
class Persona < ActiveRecord::Base
end

app/models/registro_cl2.rb
class RegistroCl2 < ActiveRecord::Base
  belongs_to :persona
end

app/models/tipo_evento.rb
class TipoEvento < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |config|
    #Configuration Options
    config.crypto_provider = Authlogic::CryptoProviders::MD5
  end
  
has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100>"}

  has_and_belongs_to_many :congresos

  easy_roles :roles

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :login,  :presence => true,
                    :length   => { :maximum => 20 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => true
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    [session_key]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paperclip_url(attachment)
    #FixMe: Esto debe buscar la url actual
    if Rails.env == "production"
      "http://congresos.uach.mx#{attachment.url}"
    elsif Rails.env == "development"
      "http://localhost:3000#{attachment.url}"
    end
  end

  def imagen?(nombre_archivo)
    nombre_separado = nombre_archivo.split "."
    extension = nombre_separado.last
    extension == "png" or extension == "jpg" or extension == "jpg" or extension == "gif"
  end
end

app/helpers/asistencia_helper.rb
module AsistenciaHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EVENTOS DIF</title>
  

<%= stylesheet_link_tag '../flutie', "bootstrap", "jquery-ui-1.8.23.custom" %>
<%= javascript_include_tag 'application' %>


  <%= csrf_meta_tags %>
    <style type="text/css">
      body { background-color: #dadada;}
    .content {
      background: #fff;
      padding: 40px;
      margin: 40px auto;
      width: 880px;
      -moz-border-radius: 24px;
      -webkit-border-radius: 24px;
    }

    </style>
    
</head>
<body>
 
<% if notice  %>
<div id="notice" class="success"><%= notice %></div>
<% end %>
<div id="structure" style="margin: auto; background:  #f6bb29">
<header>
         
        <nav class="round">
          <ul>
            <li><%= link_to "Inicio", home_path %></li>
            <% if current_user_session %>
              <li><%= link_to 'Eventos', eventos_url %></li>
            <% end %>
            <% if current_user_session and current_user.is_admin? %>
              <li> <%= link_to "Usuarios", users_path %> </li>
            <% end %>
            <% if current_user_session %>
              <li><%= link_to 'Participantes', personas_url if current_user.is_admin?%></li>
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
            <% end %>
            <% if current_user_session %>
              <li><%= link_to "Cerrar sesion", logout_url, :method => :delete %></li>
             <% else %>
              <li><%= link_to "Iniciar sesion", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>

        <%# logo = image_tag("../header2.png", :alt => "logo uach") %>
        <%#= link_to logo, root_path %>
 </header>
 <% if current_user_session %>
            <h3>Bienvenido: <%= current_user.login %></h3>
         <% end %>
 <div class="content">

   
<%= yield %>
 </div>
  <div id="FOOTER">
    <div class="creditos">DIF.  2013 <br/> Desarrollo Integral de la Familia del Estado de Chihuahua.<br/>
Av. Tecnológico 2903, Col. Magisterial 31310 <br/>
Tel. (614) 214-4000 | Fax: (614) 413-7689 <br /></div>
  </div><!-- FOOTER -->
</div>
</body>
</html>

app/views/layouts/constancias.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Constancia de Asistencia</title>
</head>
<body>
<style>
#cert{
	background:url('<%= paperclip_url(@congreso.constancias_bg)%>') no-repeat;
	width:1056px;
	height:816px;
	display:block;
	border:1px solid;
	margin:auto;
	font-family: sans-serif;
	position:relative;
	color:#7e7e7e;

}
#texto{
	position:absolute;
	top:180px;
	left:200px;
	font-size:18px;
        width:640px;
        text-align:center;
        line-height:1.3;
	text-shadow: #fff 0px 0px 20px;
}
#nombre{
	position: relative;
	display:block;
	color:#ffbf00;
	font-family:sans-serif;
	font-size:34px;
        padding:20px 0;
}
#constancia{
	color:#620055;
	font-size:60px;
	font-weight:bold;
	display:block;
	letter-spacing:10px
}
.morado{
	color:#620055;
}
</style>
  <%= yield %>
</body>
</html>